import { fail } from "assert"

const INITIAL_STATE = {
    Jpersonal: false,
    Jdeportiva: false,
    Jpapeleria: false,

    JparteMedico: false,
    JestadoFut: false,
    Pasistencia: false,
    Pcategoria: false,
    Pgrupo: false,
    Pplanearentrenamiento: false,
    Pformacionacademica: false,
    Pinformacion: false,
    Ppapeleria: false,
    Ppartidos: false,

    Ajugador: false,
    Aeventorecaudo: false,
    Aprofesor: false,
    Agrupos: false,
    Agruposmanual: false,
    Aequipos: false,
    Aacudientes: false,
    Aescuelas: false,
    Acategorias: false,
    AJinformacion: false,
    AJinformacionD: false,
    AJpapeleria: false,
    AJestadoFut: false,
    APinformacion: false,
    APpapeleria: false,
    APcategoria: false,
    APgrupos: false,
    APplanearEntre: false,
    APasistencia: false,
    APgrupo: false,
    APsede: false

}

export function counterApp(state = INITIAL_STATE, action) {
    switch (action.type) {

        //Jugador
        case 'SHOWJPERSONAL':
            return {
                Jpersonal: true,
                Jdeportiva: false,
                Jpapeleria: false,
                JparteMedico: false,
                JestadoFut: false
            }
        case 'SHOWJDEPORTIVA':
            return {
                Jdeportiva: true,
                Jpersonal: false,
                Jpapeleria: false,
                JparteMedico: false,
                JestadoFut: false
            }
        case 'SHOWJPAPELERIA':
            return {
                Jpapeleria: true,
                Jdeportiva: false,
                Jpersonal: false,
                JparteMedico: false,
                JestadoFut: false
            }
        case 'SHOWJPARTEMEDICO':
            return {
                JparteMedico: true,
                Jpapeleria: false,
                Jdeportiva: false,
                Jpersonal: false,
                JestadoFut: false
            }
        case 'SHOWJESTADOFUT':
            return {
                JestadoFut: true,
                JparteMedico: false,
                Jpapeleria: false,
                Jdeportiva: false,
                Jpersonal: false
            }


        //Profesor
        case 'SHOWPASISTENCIA':
            return {
                Pasistencia: true,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPCATEGORIA':
            return {
                Pasistencia: false,
                Pcategoria: true,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPGRUPO':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: true,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPPLANEARENTRENAMIENTO':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: true,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPFORMACIONACADEMICA':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: true,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPINFORMACION':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: true,
                Ppapeleria: false,
                Ppartidos: false,
            }
        case 'SHOWPPAPELERIA':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: true,
                Ppartidos: false,
            }
        case 'SHOWPPARTIDO':
            return {
                Pasistencia: false,
                Pcategoria: false,
                Pgrupo: false,
                Pplanearentrenamiento: false,
                Pformacionacademica: false,
                Pinformacion: false,
                Ppapeleria: false,
                Ppartidos: true,
            }

        //Adminisitrador
        case 'SHOWAJUGADOR':
            return {
                Aeventorecaudo: false,
                Ajugador: true,
                Aescuelas: false,
                Aprofesor: false,
                Agrupos: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAEVENTORECAUDO':
            return {
                Aeventorecaudo: true,
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Aequipos: false,
                Agrupos: false,
                Agruposmanual: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }

        case 'SHOWAESCUELAS':
            return {
                Aeventorecaudo: false,
                Ajugador: false,
                Aescuelas: true,
                Aprofesor: false,
                Agrupos: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPROFESOR':
            return {
                Ajugador: false,
                Aeventorecaudo: false,
                Aescuelas: false,
                Aprofesor: true,
                Aequipos: false,
                Agruposmanual: false,
                Aacudientes: false,
                Acategorias: false,
                Agrupos: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAGRUPOS':
            return {
                Ajugador: false,
                Aeventorecaudo: false,
                Aprofesor: false,
                Aequipos: false,
                Agruposmanual: false,
                Aacudientes: false,
                Acategorias: false,
                Agrupos: true,
                AJinformacion: false,
                Aescuelas: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAEQUIPOS':
            return {
                Aeventorecaudo: false,
                Ajugador: false,
                Agruposmanual: false,
                Aprofesor: false,
                Aequipos: true,
                Aescuelas: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                Agrupos: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAACUDIENTES':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Aeventorecaudo: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: true,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                Agrupos: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAGRUPOSMANUAL':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Aeventorecaudo: false,
                Agruposmanual: true,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                Agrupos: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWACATEGORIAS':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agruposmanual: false,
                Aequipos: false,
                Aescuelas: false,
                Agrupos: false,
                Aacudientes: false,
                Aeventorecaudo: false,
                Acategorias: true,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAJINFORMACION':
            return {
                Ajugador: false,
                Aescuelas: false,
                Agruposmanual: false,
                Aprofesor: false,
                Agrupos: false,
                Aeventorecaudo: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: true,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAJINFORMACIOND':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agruposmanual: false,
                Aescuelas: false,
                Agrupos: false,
                Aequipos: false,
                Aeventorecaudo: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: true,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAJPAPELERIA':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agruposmanual: false,
                Aescuelas: false,
                Agrupos: false,
                Aequipos: false,
                Aacudientes: false,
                Aeventorecaudo: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: true,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }

        case 'SHOWAJESTADOFUT':
            return {
                Ajugador: false,
                Agrupos: false,
                Aescuelas: false,
                Agruposmanual: false,
                Aprofesor: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                Aeventorecaudo: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: true,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPINFORMACION':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agrupos: false,
                Aescuelas: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: false,
                Aeventorecaudo: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: true,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPPAPELERIA':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agrupos: false,
                Agruposmanual: false,
                Aescuelas: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                Aeventorecaudo: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: true,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPCATEGORIA':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agrupos: false,
                Agruposmanual: false,
                Aequipos: false,
                Aescuelas: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                Aeventorecaudo: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: true,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPGRUPOS':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Agruposmanual: false,
                Agrupos: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                Aeventorecaudo: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: true,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPPLANEARENTRE':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Agrupos: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                Aeventorecaudo: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: true,
                APasistencia: false,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPASISTENCIA':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Agrupos: false,
                Agruposmanual: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                Aeventorecaudo: false,
                APinformacion: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: true,
                APgrupo: false,
                APsede: false
            }
        case 'SHOWAPGRUPO':
            return {
                Ajugador: false,
                Aprofesor: false,
                Agruposmanual: false,
                Aequipos: false,
                Aescuelas: false,
                Agrupos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                APpapeleria: false,
                Aeventorecaudo: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: true,
                APsede: false
            }
        case 'SHOWAPSEDE':
            return {
                Ajugador: false,
                Aprofesor: false,
                Aescuelas: false,
                Agruposmanual: false,
                Agrupos: false,
                Aequipos: false,
                Aacudientes: false,
                Acategorias: false,
                AJinformacion: false,
                AJinformacionD: false,
                AJpapeleria: false,
                AJestadoFut: false,
                APinformacion: false,
                Aeventorecaudo: false,
                APpapeleria: false,
                APcategoria: false,
                APgrupos: false,
                APplanearEntre: false,
                APasistencia: false,
                APgrupo: false,
                APsede: true
            }

        default:
            return state
    }
}